CREATE TABLE `ers_user` (
  `user_id` bigint NOT NULL AUTO_INCREMENT COMMENT '用户ID',
  `username` varchar(50) NOT NULL COMMENT '用户名',
  `password` varchar(100) NOT NULL COMMENT '密码',
  `salt` varchar(50) DEFAULT NULL COMMENT '盐',
  `real_name` varchar(50) DEFAULT NULL COMMENT '真实姓名',
  `mobile` varchar(20) NOT NULL COMMENT '手机号',
  `email` varchar(100) DEFAULT NULL COMMENT '邮箱',
  `status` tinyint DEFAULT '1' COMMENT '状态 0:禁用 1:启用',
  `blacklist_flag` tinyint DEFAULT '0' COMMENT '黑名单标记 0:否 1:是',
  `blacklist_expire_time` datetime DEFAULT NULL COMMENT '黑名单过期时间',
  `blacklist_reason` varchar(500) DEFAULT NULL COMMENT '黑名单原因',
  `last_login_time` datetime DEFAULT NULL COMMENT '最后登录时间',
  `last_login_ip` varchar(50) DEFAULT NULL COMMENT '最后登录IP',
  `register_time` datetime DEFAULT NULL COMMENT '注册时间',
  `is_promoted` tinyint DEFAULT '0' COMMENT '是否已提升为管理员 0:否 1:是',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `create_user_id` bigint DEFAULT NULL COMMENT '创建者ID',
  PRIMARY KEY (`user_id`),
  UNIQUE KEY `uk_username` (`username`),
  UNIQUE KEY `uk_mobile` (`mobile`),
  KEY `idx_status` (`status`),
  KEY `idx_blacklist` (`blacklist_flag`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户表';
